In [14]:
import numpy as np
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import PolynomialFeatures,StandardScaler
from sklearn.pipeline import Pipeline
"""
X = [[1.0, 2.0],
    [3.0, 4.0],
    [5.0, 6.0]]
"""
X = np.array([1.0,3.0,5.0])
Y =np.array([4.0,3.0,5.0])
#poly = PolynomialFeatures(include_bias=False)
#X1= poly.fit_transform(X)
p=np.polyfit(X,Y,2)
p1=np.poly1d(p)
print(np.polyval(p,X))
print(p1)
X.ndim

[4. 3. 5.]
       2
0.375 x - 2 x + 5.625


1

In [23]:
poly = PolynomialFeatures(include_bias=False,degree=2)
X1= poly.fit_transform(X)
rg=LinearRegression()
rg.fit(X1,Y)
rgy= rg.predict(X1)
print(rgy)
X1

[4. 3. 5.]


array([[ 1.,  1.],
       [ 3.,  9.],
       [ 5., 25.]])

In [21]:
rg.coef_

array([-2.   ,  0.375])

In [22]:
rg.intercept_

5.624999999999998